---
title: "PUDL Safety Hotlines Topic Model"
output: html_notebook
bibliography: Text_Mining_with_R.bibtex
---

## Load libraries
```{r}
if (!require("tidytext")) install.packages("tidytext")
if (!require("topicmodels")) install.packages("topicmodels")
library("readr")
library("tidytext")
library("dplyr")
library("magrittr")
library("topicmodels")
```

## Read the data file
```{r}
Safety_Hotline_Tickets <- read_csv(
  "~/Safety_Hotline_Tickets.csv", col_types = cols(
    Date_Created = col_date(format = "%Y-%m-%d"),
    Item_ID = col_character()))
```

## Word counts [@silge2017text, chapter 1]
```{r}
data("stop_words")
write_csv(stop_words, path = "stop_words.csv")
raw_words <- Safety_Hotline_Tickets %>% 
  select(Item_ID, Description) %>% 
  unnest_tokens(word, Description) %>% 
  anti_join(stop_words) %>% 
  write_csv(path = "raw_words.csv")
```

## Term frequency - inverse document frequency [@silge2017text, chapter 3]
```{r}
line_words <- raw_words %>% 
  count(Item_ID, word, sort = TRUE) %>% 
  ungroup()
total_words <- line_words %>% 
  group_by(Item_ID) %>% 
  summarize(total = sum(n)) %>% 
  write_csv(path = "total_words.csv")
line_words %<>% left_join(total_words) %>% 
  bind_tf_idf(word, Item_ID, n) %>% 
  write_csv(path = "line_words.csv")
safety_dtm <- line_words %>% 
  cast_dtm(Item_ID, word, n)
```

## Latent Dirichlet analysis / topic model [@silge2017text, chapter 6]
```{r}
safety_lda <- LDA(safety_dtm, k = 5, control = list(seed = 1234))
safety_topics <- tidy(safety_lda, matrix = "beta") %>% 
  write_csv(path = "safety_topics.csv")
top_terms <- safety_topics %>%
  group_by(topic) %>%
  top_n(5, beta) %>%
  ungroup() %>%
  arrange(topic, -beta) %>% 
  write_csv(path = "top_terms.csv")
```

## References
