version: '3.4'
services:
  r-base:
    build:
      context: r-base
      dockerfile: Dockerfile
      args:
        - POSTGRES_PASSWORD
    image: r-base
  postgis:
    build:
      context: postgis
      dockerfile: Dockerfile
    image: postgis
    environment:
      - POSTGRES_PASSWORD
    ports: 
      - 5439:5432
