version: '3.4'
services:
    odot-crash-data:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - odot_crash_data.env
        image: docker.io/znmeb/odot-crash-data
        ports: 
        - '5439:5432'
