version: '3.4'
services:
  rstudio:
    build:
      context: .
      dockerfile: rstudio.Dockerfile
    image: docker.io/znmeb/rstudio
    env:
      - POSTGRES_PASSWORD
    ports:
      - 8787:8787
  postgis:
    image: docker.io/znmeb/postgis
    env:
      - POSTGRES_PASSWORD
    ports: 
      - 5439:5432
